# Generated by Django 3.1.7 on 2021-03-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of menu'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Title of menu item'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Title of menu item'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Title of menu item'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name of menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitem', verbose_name='Parent menu item'),
        ),
    ]
